version: '3.4'

services:
  saas-sharp:
    image: saas-sharp
    container_name: SaaS-Sharp
    build:
      context: .
      dockerfile: Presentation.Server/Dockerfile
    ports:
        - 80:80
        - 443:443 
