name: Build-And-Test

on:
  push:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install project dependencies
      run: dotnet restore SaaS-Sharp.sln

    - name: Build projects
      run: dotnet build -c Release --no-restore SaaS-Sharp.sln
      
    - name: Run tests
      run: dotnet test -c Release --no-restore SaaS-Sharp.sln
